version: 0.0
os: linux
files:
  - source: /hoshi.js
    destination: /home/ubuntu/hoshi
  - source: /package.json
    destination: /home/ubuntu/hoshi
  - source: /config.json
    destination: /home/ubuntu/hoshi
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root
