version: 0.2

phases:
  install:
    commands:
      - npm install
      - pip3 install --upgrade awscli
  pre_build:
    commands:
      - npm test
  post_build:
    commands:
      - rm -r node_modules
      - npm install --production
artifacts:
  type: zip
  files:
    - 'src/**/*'
    - '.eslintrc.json'
    - 'example.config.json'
    - 'hoshi.js'
    - 'package-lock.json'
    - 'package.json'
    - 'yarn.lock'
